[manager]

prepend_keymap = [
    { on = ["g", "h"], run = "cd ~", desc = "Go home" },
    { on = ["g", "c"], run = "cd ~/.config", desc = "Go config" },
    { on = ["g", "d"], run = "cd ~/Downloads", desc = "Go downloads" },
    { on = ["g", "w"], run = "cd ~/Work", desc = "Go work" },
    { on = ["g", "s"], run = "cd ~/Work/system", desc = "Go system config" },
    { on = ["g", "n"], run = "cd ~/Notes", desc = "Go notes" },
    { on = ["<C-n>"], run = "shell 'ghostty &' --confirm", desc = "Open terminal here" },
]
