[manager]
prepend_keymap = [
  # Custom directory shortcuts
  { on = ["g", "h"], run = "cd ~", desc = "Go to home directory" },
  { on = ["g", "c"], run = "cd ~/.config", desc = "Go to config directory" },
  { on = ["g", "d"], run = "cd ~/Downloads", desc = "Go to Downloads" },
  { on = ["g", "w"], run = "cd ~/work", desc = "Go to work directory" },
  { on = ["g", "n"], run = "cd ~/notes", desc = "Go to notes directory" },

  # Open terminal here
  { on = ["<C-n>"], run = 'shell "foot" --confirm', desc = "Open terminal here" },
]
